config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get '/about', to:'home#about'

  get '/help', to: 'home#help'
  get '/contact', to: 'home#contact'
  get '/browse', to: 'dp_archived_objects#index'
  get '/list', to: 'dp_archived_objects#show'
  resources :dp_archived_objects

end

app/models/dp_archived_object.rb
class DpArchivedObject < ActiveRecord::Base
  has_many :dp_object_instances, foreign_key: 'on_object_ao_id'
end

app/models/dp_archived_objects_view.rb
class OracleBase < ActiveRecord::Base
  self.abstract_class = true
  establish_connection (:default)
end


class DpArchivedObjectsView < OracleBase
  self.table_name = "DIVA.DP_ARCHIVED_OBJECTS_VIEW"
end

app/models/dp_distinct_obj_tapes_view.rb
class OracleBase < ActiveRecord::Base
  self.abstract_class = true
  establish_connection (:default)
end


class DpDistinctObjTapesView < OracleBase
  self.table_name = "DIVA.DP_DISTINCT_OBJ_TAPES_VIEW"
  belongs_to :dp_tape, foreign_key: "ta_barcode"
end

app/models/dp_object_instance.rb
class DpObjectInstance < ActiveRecord::Base
  belongs_to :dp_archived_object, foreign_key: 'on_object_ao_id'
end

app/models/dp_tape.rb
class DpTape < ActiveRecord::Base
  has_many :dp_distinct_obj_tapes_view, primary_key: "ta_barcode", foreign_key: "ta_barcode"
end

app/controllers/application_controller.rb
require 'faraday'
require 'faraday_middleware'

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :check_session
  protect_from_forgery with: :exception
  def index
    render html: "Welcome to SeaBass DV!"
  end

  def check_session
    if session[:current_session_code].nil?
      register = "http://127.0.0.1:9763/services/DIVArchiveWS_REST_2.1/registerClient"
      conn = Faraday.new(:url => register) do |builder|
        builder.request :url_encoded
        builder.response :xml,  :content_type => /\bxml$/ #logging stuff
        builder.adapter Faraday.default_adapter
      end
      res = conn.get do |request|
        request.url register, :appName => "DIVA_WS_TEST", :locName => "MX", :processId => "456576"
      end
      if res.success?
        session[:current_session_code] = res.body["registerClientResponse"]["return"]
      else
        redirect_to :root
      end
    end
  end

end

app/controllers/dp_archived_objects_controller.rb
class DpArchivedObjectsController < ApplicationController
  def index
    if params[:search]
      @step = "%#{params[:search]}%"
      @data = DpArchivedObjectsView.joins("INNER JOIN dp_distinct_obj_tapes_view ON dp_archived_objects_view.ao_object_name = dp_distinct_obj_tapes_view.te_object_name INNER JOIN dp_tapes ON dp_distinct_obj_tapes_view.ta_barcode = dp_tapes.ta_barcode").select('dp_archived_objects_view.*,dp_tapes.*').where("ao_object_name LIKE ? AND TA_GROUP_TG_ID = ?","#{@step}", "45")
    else
      @data = ""
    end
    #@data = DpArchivedObjectsView.where("ao_object_name LIKE ?","%993687%")

    #@data = DpArchivedObject.joins(:dp_object_instances).where("ao_object_name LIKE ?","%993687%")
  end
  def show
    @data = params[:post]
    #@data = DpArchivedObjectsView.where("ao_object_name LIKE ?","%993687%")
    #@data = DpArchivedObject.where("ao_object_name LIKE ?","%993687%")
  end
end

app/controllers/dp_object_instances_controller.rb
class DpObjectInstancesController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about

  end

  def help
  end
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "SeaBassDV - Archive Utility"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/dp_archived_objects_helper.rb
module DpArchivedObjectsHelper
end

app/helpers/dp_object_instances_helper.rb
module DpObjectInstancesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/dp_archived_objects/index.html.erb
<h1>DIVA Archived Objects</h1>
<p>Please enter a search term:</p>
<%= form_tag(browse_path, :method => "get", class: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search by file name...", class: "form-control" %>
<% end %>
<p></p>
<% if @data.present? %>
  <%= form_tag(list_path, :method => "get") do %>
    <table id="example" class="table table-hover table-condensed">
      <!-- <tr><td><%= @step %></td></tr> -->
      <thead>
        <tr>
          <th></th>
          <th>NAME</th>
          <th>CATEGORY</th>
          <th>BARCODE</th>
          <th>ONLINE?</th>
        </tr>
      </thead>
      <tbody>
      <% @data.each do |data| %>
        <% if data.ta_is_online == "N" %>
          <tr class="danger">
            <td><%= check_box_tag :barcodes, data.ta_barcode, true, name:'post[barcodes][]' %></td>
        <% else %>
          <tr>
            <td><%= check_box_tag :barcodes, data.ta_barcode, false, name:'post[barcodes][]' %></td>
        <% end %>
            <td><%= data.ao_object_name %></td>
            <td><%= data.ao_category %></td>
            <td><%= data.ta_barcode %></td>
            <td><%= data.ta_is_online %></td>
          </tr>
      <% end %>
    </tbody>
    </table>
    <p><%= submit_tag "Print Retrieve List", id: "print", class: "btn btn-primary" %></p>
  <% end %>
<% else %>
  <% if params[:search].present? %>
    <p>There are no files containing the term(s) <%= params[:search] %>.</p>
  <% end %>
<% end %>

app/views/dp_archived_objects/show.html.erb
<h1>List of Barcodes to Retrieve</h1>
<% if @data.present? %>
  <!-- <%= @data %> -->
  <table class="table table-hover table-condensed">
    <!-- <tr><td><%= @step %></td></tr> -->
    <tr>
      <th>BARCODE</th>
    </tr>
    <% data_uniq = @data[:barcodes].uniq %>
    <% data_uniq.sort!.each do |data| %>
      <tr>
        <td><%= data %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <p>There are no barcodes selected.</p>
<% end %>
<%= link_to '<< Back to Results', :back, class: "btn btn-primary" %>

app/views/home/about.html.erb
<% provide(:title, "About") %>
  <h1>About</h1>
  <p>Written to provide OTT functions not Available in DIVA Director</p>

app/views/home/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the MX Team about SeaBass DV at
  <a href="mailto:tvcmxsupport@cbs.com">TVC MX Support</a>.
</p>

app/views/home/help.html.erb
<% provide(:title, "Help") %>
  <h1>Help</h1>
  <p>Get help on the SeaBass DV application at: <a href="#">Under Construction</a></p>

app/views/home/index.html.erb
<div class="center jumbotron">
  <h1>SeaBass DV - Archive Utility</h1>
  <%= image_tag("bass.jpg", alt:"Bass Logo") %>
  <h2>
    This is the home page for the SeaBass DV application.  To be used for finding files and tapes in the
    <a href="http://10.103.0.244">CBS DIVA archive</a>
  </h2>
  <%= link_to "Browse the Library Now!", browse_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails Logo"), 'http://rubyonrails.org/' %>

app/views/layouts/_data.html.erb
<table>
  <tr><td><%= @step %></td></tr>
  <tr>
    <th>TE_OBJECT_NAME</th>
    <th>TE_CATEGORY</th>
    <th>TA_BARCODE</th>
    <th>ONLINE?</th>
  </tr>
  <% @data.each do |data| %>
  <tr>
    <td><%= data.te_object_name %></td>
    <td><%= data.te_category %></td>
    <td><%= data.ta_barcode %></td>
    <td><%= data.ta_is_online %></td>
  </tr>
  <% end %>
</table>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://10.102.129.110/index.php">MX Home</a>
    <a href="http://10.103.0.244/">DIVA Director</a>
    Session ID:= <%= session[:current_session_code] if !session[:current_session_code].nil? %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "SeaBass DV", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
  <script type="text/javascript" class="init">
  $(document).ready( function () {
      var table = $('#example').DataTable({"stateSave":true,"serverSide":false, "bPaginate":false});

      /* $('#print').click( function() {
        var data = table.$('input, select').serialize();
        alert ("The data: \n\n"+data.substr(0,120)+'...');
        return true;
      } ); */
  } );
  </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %> | SeaBass DV - Archive Utility</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
  </body>
</html>